// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cppstuff.proto
#ifndef GRPC_cppstuff_2eproto__INCLUDED
#define GRPC_cppstuff_2eproto__INCLUDED

#include "cppstuff.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace cppstuff {

// The greeting service definition.
class CppStuff final {
 public:
  static constexpr char const* service_full_name() {
    return "cppstuff.CppStuff";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::cppstuff::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::cppstuff::CarParkStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>> AsyncGetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>>(AsyncGetCarParkStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>> PrepareAsyncGetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>>(PrepareAsyncGetCarParkStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>* AsyncGetCarParkStatusRaw(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cppstuff::CarParkStatusResponse>* PrepareAsyncGetCarParkStatusRaw(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::cppstuff::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::cppstuff::CarParkStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>> AsyncGetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>>(AsyncGetCarParkStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>> PrepareAsyncGetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>>(PrepareAsyncGetCarParkStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCarParkStatus(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cppstuff::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::cppstuff::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>* AsyncGetCarParkStatusRaw(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cppstuff::CarParkStatusResponse>* PrepareAsyncGetCarParkStatusRaw(::grpc::ClientContext* context, const ::cppstuff::CarParkStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCarParkStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response);
    virtual ::grpc::Status GetCarParkStatus(::grpc::ServerContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::cppstuff::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::cppstuff::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCarParkStatus(::grpc::ServerContext* context, ::cppstuff::CarParkStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::cppstuff::CarParkStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_GetCarParkStatus<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cppstuff::HelloRequest, ::cppstuff::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cppstuff::HelloRequest* request, ::cppstuff::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::cppstuff::HelloRequest, ::cppstuff::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cppstuff::HelloRequest, ::cppstuff::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::cppstuff::CarParkStatusRequest, ::cppstuff::CarParkStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cppstuff::CarParkStatusRequest* request, ::cppstuff::CarParkStatusResponse* response) { return this->GetCarParkStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetCarParkStatus(
        ::grpc::MessageAllocator< ::cppstuff::CarParkStatusRequest, ::cppstuff::CarParkStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cppstuff::CarParkStatusRequest, ::cppstuff::CarParkStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCarParkStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_GetCarParkStatus<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCarParkStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCarParkStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCarParkStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cppstuff::HelloRequest, ::cppstuff::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cppstuff::HelloRequest, ::cppstuff::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::cppstuff::HelloRequest* /*request*/, ::cppstuff::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cppstuff::HelloRequest,::cppstuff::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCarParkStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCarParkStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cppstuff::CarParkStatusRequest, ::cppstuff::CarParkStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cppstuff::CarParkStatusRequest, ::cppstuff::CarParkStatusResponse>* streamer) {
                       return this->StreamedGetCarParkStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCarParkStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCarParkStatus(::grpc::ServerContext* /*context*/, const ::cppstuff::CarParkStatusRequest* /*request*/, ::cppstuff::CarParkStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCarParkStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cppstuff::CarParkStatusRequest,::cppstuff::CarParkStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_GetCarParkStatus<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_GetCarParkStatus<Service > > StreamedService;
};

}  // namespace cppstuff


#endif  // GRPC_cppstuff_2eproto__INCLUDED
